dist: bionic
language: python
python: 3.8

install:
  - pip install kodi-addon-checker

before_script:
- git config core.quotepath false

# command to run our tests
script:
  - kodi-addon-checker --branch=BRANCH_NAME $([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo --higher-version-required $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq))

notifications:
  email:
    on_failure: change # default: always
